### ISSUE TITLE
cannot import name 'InteractiveBeamSearchSampler' from 'keras_wrapper.model_ensemble'

### ISSUE THREAD

**Issue by trungjune** [lvapeab/nmt-keras#104]
Help me, I encountered an error when run sample_server.py
(keras) viegrid@VIEGRID-SV-GPU:~/trung/keras-gpu/nmt-keras/demo-web$ python ./sample_server.py --dataset datasets/Dataset.pkl --port=6542/
Traceback (most recent call last):
  File "./sample_server.py", line 21, in <module>
    from keras_wrapper.model_ensemble import InteractiveBeamSearchSampler
ImportError: cannot import name 'InteractiveBeamSearchSampler' from 'keras_wrapper.model_ensemble' (/home/viegrid/trung/keras-gpu/nmt-keras/src/keras-wrapper/keras_wrapper/model_ensemble.py)

**Comment by lvapeab** [comment]
Sorry for the late response. Yo need to checkout the `Interactive_NMT` branch from the `Multimodal Keras Wrapper`:

`cd /home/viegrid/trung/keras-gpu/nmt-keras/src/keras-wrapper/; git checkout Interactive_NMT`
