### ISSUE TITLE
What dose the FC mean in nmt-keras architecture?

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#11]
Hi~
Can you give me a brief explanation about the FC mean in nmt-keras architecture?
Thanks!

**Comment by lvapeab** [comment]
Hi @hanyaqian,
do you refer to the FC layers that appear in the figure?

Those layers represent a deep output layer (see https://arxiv.org/pdf/1312.6026.pdf). For an instantiation of this architecture in a NMT context, refer to appendix A.2.2 from https://arxiv.org/abs/1409.0473.

Cheers.

**Comment by hanyaqian** [comment]
Hi @lvapeab

Thank you recommend those paper for me, i will read carefully!
