### ISSUE TITLE
Introduce a setup.py for pip installations

### ISSUE THREAD

**Issue by davidwilby** [lvapeab/nmt-keras#114]
Will you consider introducing a `setup.py` for nmt-keras so that it can be installed via
```shell
pip install git+https://github.com/lvapeab/nmt-keras.git#egg=nmt_keras
```
similarly to `keras_wrapper`

**Comment by lvapeab** [comment]
Yes, this is a valuable addition. Feel free to open a PR if you want to add it. Otherwise, I'll do that next weekend.
Cheers!

**Comment by davidwilby** [comment]
Sweet, I'll check it out this week.

**Comment by davidwilby** [comment]
Looking at this in PR: https://github.com/lvapeab/nmt-keras/pull/115

**Comment by lvapeab** [comment]
Done and merged https://github.com/lvapeab/nmt-keras/pull/115.
