### ISSUE TITLE
Support of TensorFlow >=2.0

### ISSUE THREAD

**Issue by davidwilby** [lvapeab/nmt-keras#116]
Hey, do you know if NMT-keras works with TF2 at this point?

**Comment by lvapeab** [comment]
Not at this point. We'll need to update the TF backend of [MarcBS/keras](https://github.com/MarcBS/keras/blob/master/keras/backend/tensorflow_backend.py) to TF2 (using `compat.v1` imports).

**Comment by davidwilby** [comment]
Okay, thanks @lvapeab that's what I suspected.
