### ISSUE TITLE
Support for Factored Models ?

### ISSUE THREAD

**Issue by PVinay737** [lvapeab/nmt-keras#117]
Is it possible to include lingustic features such as [factors](https://www.researchgate.net/publication/221013253_Factored_Translation_Models) that could improve the translation  with this toolkit ?

**Comment by lvapeab** [comment]
If you refer to specific architectures for factored NMT (e.g. [Burlot et al., 17](https://www.aclweb.org/anthology/W17-4703.pdf)), not directly out of the box. You'll need to make the corresponding  modifications to the [model architecture](https://github.com/lvapeab/nmt-keras/blob/670990158263cfe714b4abae4863ded457e2493e/nmt_keras/model_zoo.py#L435).
