### ISSUE TITLE
 the translation performances of nmt-keras

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#12]
Hi @lvapeab 

Can you show me some experimental results about  the translation performances measured in BLEU score by using nmt-keras?

Thank you very much!

**Comment by Sasanita** [comment]
What exactly do you need @hanyaqian? Some example of val.coco file? 
iteration,Bleu_1,Bleu_2,Bleu_3,Bleu_4,CIDEr,METEOR,ROUGE_L,TER,
3000,0.598092828287,0.465452429216,0.37225359929,0.300590340743,2.5149261755,0.52171360926,0.574988480493,0.528963191084,
6000,0.596200830235,0.460011724321,0.366499073456,0.295672394729,2.4501395815,0.52131686399,0.570863282666,0.544947939581,
9000,0.618178862991,0.482973484766,0.388393293651,0.315205571049,2.61521979568,0.535978639985,0.588365585636,0.519313682358,
12000,0.598055536415,0.463311430953,0.369795372604,0.298142205599,2.49861084418,0.521315886727,0.570351138997,0.538524710368,
15000,0.607211086267,0.475216838512,0.381389671454,0.308821456641,2.6397335786,0.537407952525,0.588491458891,0.506613873002,
18000,0.611814575383,0.478420454156,0.384145667843,0.311012721313,2.62818046103,0.533914822694,0.587978569533,0.510984015252,
21000,0.602130985145,0.470215643585,0.377707347271,0.306441325217,2.57493799204,0.530693556495,0.580710565974,0.513330400352,
24000,0.592082862676,0.46234629123,0.371296441776,0.300142760253,2.59478457025,0.52435731579,0.579246330301,0.512450505939,
27000,0.590195110669,0.458354556508,0.367002730048,0.296232668087,2.5735539167,0.518618981995,0.57580558499,0.522158674292,
30000,0.611233864403,0.474162681225,0.378635181579,0.305124267373,2.57876233594,0.528784769364,0.584942580434,0.528493914064,
33000,0.597837882009,0.467462233273,0.376589775146,0.306296212065,2.59420688038,0.529375348883,0.576583334388,0.524270420883,
36000,0.59673748203,0.461503028161,0.367297132889,0.295526478485,2.5109315528,0.513648474224,0.568255762936,0.551752456372,
39000,0.614234265782,0.479699368655,0.385348045262,0.312792444795,2.67047002655,0.535784654519,0.591603769944,0.507933714621,
42000,0.583984466067,0.453747591666,0.363375075867,0.293829459363,2.5219811058,0.514898722626,0.571588589975,0.526792784866,
45000,0.608831035342,0.476205040753,0.383641238516,0.312698888076,2.65558109974,0.535730670359,0.584987124641,0.514679571785,
48000,0.592546805934,0.461648478755,0.369237297873,0.298369230886,2.56906605947,0.521873648964,0.575690012854,0.524475729579,
51000,0.595917458306,0.463908001348,0.371092366616,0.29988409904,2.62550238903,0.528621633481,0.581201758065,0.519020384221,
54000,0.601775265631,0.46945349886,0.376399194872,0.305308165052,2.61643425235,0.529677120683,0.579271514997,0.513418389793,
57000,0.597244545916,0.463823379777,0.370121058198,0.298539556492,2.57529716649,0.522254487128,0.577293139689,0.527936647602,
60000,0.606994842115,0.475826089003,0.383845935578,0.312556828455,2.6607473307,0.534688631794,0.585595815336,0.514972869922,
63000,0.60496812113,0.473817287203,0.381244909982,0.310410796462,2.64728892227,0.531472147276,0.584719280291,0.517817861857,
66000,0.609315321781,0.475880353407,0.382308669531,0.310375209657,2.68040072629,0.53479617436,0.58577461529,0.513154421469,
69000,0.614655073148,0.477814529128,0.38234471209,0.309031571024,2.61987941158,0.532757738159,0.583555665741,0.524534389207,

**Comment by lvapeab** [comment]
If you refer to translation performance in general, it should be comparable to other NMT systems, such as nematus or OpenNMT. A well-tuned NMT system should have a similar performance (or better) than Moses, especially using ensembing decoding. 

In my experiments, results using a single system are slightly below Moses when using a single system (in general). Nevertheless, using an ensemble, I usually beat Moses. Note that these results depend on the task and the language.

Unfortunately, I (still) don't have any systematic comparison against other NMT/SMT toolkits. But it would be nice to have it :)

**Comment by hanyaqian** [comment]
@Sasanita @lvapeab, sorry,  did`t reply in time.

I recently prepared an interview, unfortunately, i did not pass it. 

Thanks!
