### ISSUE TITLE
Confusion with opennmt-tf

### ISSUE THREAD

**Issue by nashid** [lvapeab/nmt-keras#122]
I am a bit confused when to adopt which framework with keras? Also what is difference between opennmt-tf (https://github.com/OpenNMT/OpenNMT-tf) vs nmt-keras?

Also how does it differ than simply using https://github.com/keras-team/keras/blob/master/examples/lstm_seq2seq.py

**Comment by lvapeab** [comment]
Well, now that Keras has been integrated into TF, it's all a little bit convoluted. NMT-Keras uses an extended version of `keras` (NOT `tf.keras`).
  
`OpenNMT-tf` makes use of `tf.keras`, as part of the TF ecosystem.

 https://github.com/keras-team/keras/blob/master/examples/lstm_seq2seq.py
is a simple Seq2Seq model, that lacks several features, such as attention mechanisms or beam search.
