### ISSUE TITLE
Missing auto setup of required packages for running this library

### ISSUE THREAD

**Issue by nashid** [lvapeab/nmt-keras#123]
`requirements.txt` file is missing.

As per Installation doc:

```
git clone https://github.com/lvapeab/nmt-keras
cd nmt-keras
pip install -r requirements.txt
```

I see in the last commit this file was removed . 
https://github.com/lvapeab/nmt-keras/pull/121

And now we have to manually installed the requited dependencies.

**Comment by lvapeab** [comment]
Docs seem to be out-dated. I'll update them.

You should follow the `README.md`:


Assuming that you have [pip](https://en.wikipedia.org/wiki/Pip_(package_manager)) installed and updated (>18), run:
  
  ```bash
  git clone https://github.com/lvapeab/nmt-keras
  cd nmt-keras
  pip install -e .
  ```
