### ISSUE TITLE
How to use pretrained word2vec embeddings?

### ISSUE THREAD

**Issue by nashid** [lvapeab/nmt-keras#124]
Is there code sample/example of a project how to use pretrained word2vec embeddings?

**Comment by lvapeab** [comment]
You need to preprocess your embeddings, either binary or text: 

```
python utils/preprocess_binary_word_vectors.py -v input_vectors.bin -d word2vec.en
```

And tell the `config.py` to use them (and the same for the target lanaguge):

https://github.com/lvapeab/nmt-keras/blob/ab29848df8001f1abf58f5294c8e0c1ae78ac23e/config.py#L190
