### ISSUE TITLE
Can not 2_training_tutorial.ipynb with jupyter notebook

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#13]
Hi @lvapeab 

When i try to open the 2_training_tutorial.ipynb in Jupyter notebook happenning a error

`Unreadable Notebook: F:\NMT\nmt-keras\examples\2_training_tutorial.ipynb AttributeError('metadata',)`

Regards!

**Comment by lvapeab** [comment]
Hello @hanyaqian, 

thanks, there was a minor bug in that tutorial. I've just pushed the fix (https://github.com/lvapeab/nmt-keras/commit/773d91b2e4636c459094b2601272abf7a9e6324f).

Cheers!

**Comment by hanyaqian** [comment]
Hi @lvapeab , It works. 

>_<

Thanks.
