### ISSUE TITLE
Sampling decoding

### ISSUE THREAD

**Issue by philipcori** [lvapeab/nmt-keras#131]
Hello, I am trying to use a sampling decoding strategy rather than beam search. It is not totally clear to me how to implement this from the documentation, however it seems like it is supported by this or the keras-wrapper library. What function should be used to do this (rather than predictBeamSearchNet())? Would I set ```'sampling'``` to ```'multinomial'``` in params_prediction? I am trying to move away from beam search decoding. Thanks!

**Comment by lvapeab** [comment]
The models defined here are meant to be used with beam search, as they are autoreggressive (see [Sec. 2 of this paper](https://arxiv.org/pdf/1711.02281.pdf)). 

Of course, the `keras-wrapper` library supports regular sampling  (sample from a distribution probability, given by a model), as done for example by a classifier. 

Non-autoreggressive NMT is not implemented here. If you want to use it, you should modify the models and implement something similar to the paper above. 

If you want to stick to autoreggressive NMT, simply generating the most-likely token (or a token sampled from the model's distribution), you can set the beam size to 1. Moreover, if that's you use case, you can create some sort of `predictGreedySearchNet` function, that doesn't require all the beam search logic. PRs are welcome :)
