### ISSUE TITLE
Strange behavior with plotting metrics for validation

### ISSUE THREAD

**Issue by NamTran838P** [lvapeab/nmt-keras#133]
I use the coco evaluation package and the built-in plotting option to plot metrics for validation. Plots at various epochs are included. I notice that for the first few epochs, the plots are empty even though coco evaluation still occurs. Only at epoch 6 do we see some plotting output, but even then it looks shifted. Any help with this is really appreciated!

![epoch_3](https://user-images.githubusercontent.com/26189749/80892786-a24f5780-8c81-11ea-91e6-cc2dc0bd18a1.jpg)
Epoch 3

![epoch_5](https://user-images.githubusercontent.com/26189749/80892784-a11e2a80-8c81-11ea-98ad-aa66aeadf11e.jpg)
Epoch 5

![epoch_6](https://user-images.githubusercontent.com/26189749/80892785-a1b6c100-8c81-11ea-850b-0a14c15fa70f.jpg)
Epoch 6

**Comment by lvapeab** [comment]
Hmm, strange indeed. I've made a couple of minor updates to the plotting function. Please, update your `multimodal-keras-wrapper` to get it working. I've also added an option in `config.py` to manually specify the Y-axis of the figure. 

Setting `PLOT_EVALUATION = True` and `METRICS = ['coco']` I obtain this plot:

![epoch_8](https://user-images.githubusercontent.com/4717075/80911785-de91bf00-8d38-11ea-8386-0926796dfa4c.jpg)

**Comment by NamTran838P** [comment]
Thanks it works now.
