### ISSUE TITLE
Conversion to TFJS

### ISSUE THREAD

**Issue by AmitMY** [lvapeab/nmt-keras#142]
I'm looking for an NMT framework that can run inference client-side in the browser.

Does `nmt-keras` support the usual Keras conversion to tfjs?

Like:
```bash
tensorflowjs_converter --input_format=keras model.h5 web_model
```

Is there any client-only demo out there?

**Comment by lvapeab** [comment]
Hi,

unfortunately I've never tried converting a model to tfjs and as far as I know, there are no examples of that. Feel free to try the conversion, but you'll probably need to hack a couple of things in order to get things working with TF v1 and (maybe) with our custom layers.
