### ISSUE TITLE
Example Colab Fails 

### ISSUE THREAD

**Issue by AmitMY** [lvapeab/nmt-keras#143]
The example colab:
https://colab.research.google.com/github/lvapeab/nmt-keras/blob/master/examples/tutorial.ipynb#scrollTo=hiY2fUFU83Rx

Fails:
![image](https://user-images.githubusercontent.com/5757359/127269379-c3ba0952-1968-4626-8fba-a59a8aead9bf.png)

Probably was made for tf1, but installs tf2.

Install cell:
![image](https://user-images.githubusercontent.com/5757359/127269556-aac0e21b-6584-4e51-b824-b1f0de17398e.png)

**Comment by lvapeab** [comment]
Thanks for alerting. Indeed, Colab installs a bunch of packages that end up installing TF2 as a dependency. I've updated the notebooks.
