### ISSUE TITLE
a small bug in 3_decoding_tutorial

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#15]
Hi @lvapeab 

`params_prediction = {'batch_size': 50,
                     'n_parallel_loaders': 8,
                     'predict_on_sets': ['test'],
                     'beam_size': 12,
                     'maxlen': 50,
                     'model_inputs': ['source_text', 'state_below'],
                     'model_outputs': ['target_text'],
                     'dataset_inputs': ['source_text', 'state_below'],
                     'dataset_outputs': ['target_text'],
                     'normalize': True,
                     'alpha_factor': 0.6                   
                     }`

may be modified to:

`params_prediction = {'max_batch_size': 50,
                     'n_parallel_loaders': 8,
                     'predict_on_sets': ['test'],
                     'beam_size': 12,
                     'maxlen': 50,
                     'model_inputs': ['source_text', 'state_below'],
                     'model_outputs': ['target_text'],
                     'dataset_inputs': ['source_text', 'state_below'],
                     'dataset_outputs': ['target_text'],
                     'normalize': True,
                     'alpha_factor': 0.6                   
                     }`

batch_size -> max_batch_size

**Comment by lvapeab** [comment]
Hi @hanyaqian,

thank you for detecting the bug. Indeed, this was a bug due to a refactoring. I've just corrected it.

Thanks!
