### ISSUE TITLE
a small problem in config.py

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#18]
Hi @lvapeab 

1. What is it for you to say that using batches with homogeneous output lengths and using dropout in recurrent layers is dangerous? [here](https://github.com/lvapeab/nmt-keras/blob/master/config.py#L123) and [here](https://github.com/lvapeab/nmt-keras/blob/master/config.py#L188)
2. What is the meaning of vqa? [here](https://github.com/lvapeab/nmt-keras/blob/master/config.py#L216)

Regards!

**Comment by lvapeab** [comment]
Hi @hanyaqian,

1.1 The "homogeneous batches" setting is somehow buggy. I've don't know exactly the problem. As I have some time, I'll try to fix it.

1.2 It is not straightforward to apply dropout to recurrent layers, as it can have unexpected effects. It is safer to apply dropout to the input of the RNN, not to the recurrent connections. Nevertheless, take a look to this paper for furthest discussion: https://arxiv.org/pdf/1512.05287.pdf

2. VQA stands for 'visual question answering'. See the [VQA challenge](http://www.visualqa.org/). The keras wrapper is prepared for store the output in the format required by this challenge. Nevertheless, the 'vqa' tag might be confusing in the config file. I'll remove it for the sake of clarity ;)

**Comment by hanyaqian** [comment]
Hi @lvapeab 

Your work is fantastic and thank you very much.
