### ISSUE TITLE
Be confused about ctx mean

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#19]
Hi @lvapeab

I am reading your code line by line, and now be some confused with the ctx mean. in [here](https://github.com/lvapeab/nmt-keras/blob/master/model_zoo.py#L323)

Regards!

**Comment by lvapeab** [comment]
Hi, 
if you recall  (see the expression before Eq. 7 from this paper: https://arxiv.org/pdf/1502.03044.pdf), the decoder hidden state is initialized according to  a MLP, which takes a representation of the source sentence. Here, as representation of the source sentence, we take the mean of the states of the BRNN encoder .
Of course, there are other options. One could use, for example, the last hidden state of the BLSTM as input to the MLP. I think it also could work well, but I haven't try it yet :)
