### ISSUE TITLE
How to remove keras_wrapper from my linux  environment？

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#21]
Hi @lvapeab 

I want to remove the previous keras_wrapper from linux environment, and reimplement the keras_wrapper from scratch. I had deleted the keras_wrapper path from ~/.bashrc, but it still not work.

`File "build/bdist.linux-x86_64/egg/keras_wrapper/dataset.py", line 859, in setOutput`

**Comment by lvapeab** [comment]
Hi,
how did you install the Wrapper?
You can uninstall it from pip with:
`pip uninstall Multimodal-Keras-Wrapper`

Or directly removing (`rm -rf`) the sources from wherever you installed the package.
