### ISSUE TITLE
 Confused on several concepts

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#23]
Hi @lvapeab 

Can you help me explain the following concepts? I am a bit confused when reading the source code of keras.

- inbound_layers
- outbound_layer  [here](https://github.com/MarcBS/keras/blob/master/keras/engine/topology.py#L75-#L80)
- inbound_nodes 
- outbound_nodes [here](https://github.com/MarcBS/keras/blob/master/keras/engine/topology.py#L203-#L204)

Regards

**Comment by lvapeab** [comment]
This is the way that Keras has for constructing/managing the (Theano/Tensorflow/CNTK) computation graph of a given network. Maybe you should better ask in some Keras forum. You'll probably get better explanations than those I can give you ;)
