### ISSUE TITLE
Is it possible to use this model to use aligned monolingual word embeddings, without any parallel data?

### ISSUE THREAD

**Issue by jamsheer2u** [lvapeab/nmt-keras#32]
Can we have a sample/tutorial explaining how Align monolingual word embeddings from https://github.com/facebookresearch/MUSE . 

I have 2 pre-trained aligned vectors, and I want to use these vectors and get the translations **without using any parallel data**. Is this possible with this Model? How the model can be trained in this scenario?

**Comment by lvapeab** [comment]
Hello @jamsheer2u ,

do you refer to the model of Figure 2 from https://arxiv.org/pdf/1711.00043.pdf ?

If so, this kind of models are not implemented in this repository. It would be really nice if someone wants to implement it  ;)

**Comment by jamsheer2u** [comment]
@lvapeab thanks, I am still trying to understand that paper. I speak a low resource language - Malayalam. It is very difficult to get parallel data for this language. So, I am trying to build an NMT for it.
