### ISSUE TITLE
Problems with coverage penalty  

### ISSUE THREAD

**Issue by yftah89** [lvapeab/nmt-keras#35]
Hi :)
When I'm changing the coverage to true : 
COVERAGE_PENALTY = True                      # Apply source coverage penalty
COVERAGE_NORM_FACTOR = 0.2                    # Coverage penalty factor

I get the following error on evaluation time : 
nmt-keras/src/keras-wrapper/keras_wrapper/cnn_model.py", line 2140, in predictBeamSearchNet
    length_penalties = [1.0 for _ in len(samples)]
TypeError: 'int' object is not iterable

I don't know if its matter but the length penalty is still set to False.
I think that the same problem will return on line 2272 in the same file: 
coverage_penalties = [0.0 for _ in len(samples)]

Thanks again for all of your help, I'm really appreciating it .

**Comment by lvapeab** [comment]
Hello @yftah89 ,

thank you for noticing it. I've fixed that bug (https://github.com/lvapeab/multimodal_keras_wrapper/commit/3b2cc5f8b91320fabad01de7fd91e6732b09a7ad). You should update the [Multimodal Keras Wrapper](https://github.com/lvapeab/multimodal_keras_wrapper). 

Cheers!

**Comment by yftah89** [comment]
Thanks :)
working just fine now.
