### ISSUE TITLE
I'd like to achieve a NMT

### ISSUE THREAD

**Issue by yanmengqi** [lvapeab/nmt-keras#39]
Hello,I'd like to achieve Chinese and English Neural Machine Translation，Can I just change the training set（Chinese and English）?
Do I need other operation?

**Comment by lvapeab** [comment]
Hello,

for avoiding problems, you should check that your Chinese files are encoded as utf-8. Moreover, it is recommended to apply some word segmenter to the Chinese corpora, prior to any other operation (e.g. [the Standford segmenter](https://nlp.stanford.edu/software/segmenter.html)).

**Comment by yanmengqi** [comment]
Thank you .
Does the demo-web using the model that trained from EuTrans?
Another question,I have tried use the demo-web,but when I click the translate button,there returned some php wrong:
<?php

# make sure that only one script at a time accesses the sampling server
$fp = fopen('/tmp/flock', 'w');

function file_get_contents_utf8($fn) {
     $content = file_get_contents($fn);
      return mb_convert_encoding($content, 'UTF-8',
          mb_detect_encoding($content, 'UTF-8, ISO-8859-1', true));
}


if (flock($fp, LOCK_EX))
{
	$source=$_GET['source'];
	$url = 'http://localhost:8888/?source='.urlencode($source);
    $out = file_get_contents($url);
	echo $out;
}
else
{
	echo "Server timeout! Try again later.";
}

?>


Maybe I forget install something?

**Comment by yanmengqi** [comment]
<?php

# make sure that only one script at a time accesses the sampling server
$fp = fopen('/tmp/flock', 'w');

function file_get_contents_utf8($fn) {
     $content = file_get_contents($fn);
      return mb_convert_encoding($content, 'UTF-8',
          mb_detect_encoding($content, 'UTF-8, ISO-8859-1', true));
}


if (flock($fp, LOCK_EX))
{
	$source=$_GET['source'];
	$url = 'http://localhost:8888/?source='.urlencode($source);
    $out = file_get_contents($url);
	echo $out;
}
else
{
	echo "Server timeout! Try again later.";
}

?>

**Comment by yanmengqi** [comment]
`<?php

# make sure that only one script at a time accesses the sampling server
$fp = fopen('/tmp/flock', 'w');

function file_get_contents_utf8($fn) {
     $content = file_get_contents($fn);
      return mb_convert_encoding($content, 'UTF-8',
          mb_detect_encoding($content, 'UTF-8, ISO-8859-1', true));
}


if (flock($fp, LOCK_EX))
{
	$source=$_GET['source'];
	$url = 'http://localhost:8888/?source='.urlencode($source);
    $out = file_get_contents($url);
	echo $out;
}
else
{
	echo "Server timeout! Try again later.";
}

?>`

**Comment by lvapeab** [comment]
Did you follow the steps required for running the demo?: https://github.com/lvapeab/nmt-keras/tree/master/demo-web

If so, you must check your php configuration

**Comment by yanmengqi** [comment]
Very thank you.I am committed to using Keras to achieve Chinese and English translation.I will have a try.
