### ISSUE TITLE
ImportError: No module named beam_search_interactive

### ISSUE THREAD

**Issue by yanmengqi** [lvapeab/nmt-keras#40]
I want to run the code in demo-web, but I always get this error when I use this command to start the php server.
`python ./sample_server.py --dataset datasets/Dataset.pkl --port=8888  
        --config trained_models/config.pkl --models trained_models/update_15000`

**Comment by yanmengqi** [comment]
Ok,I will have a try.Thank you.

**Comment by hiteshvaidya** [comment]
@yanmengqi did you find the folder `multimodal_keras_wrapper`? Where is it? I am facing the same issue. I didn't get that folder.

**Comment by hiteshvaidya** [comment]
I was getting the same error and I followed the step suggested by @lvapeab. However, after that I am getting another error as follows,
`ImportError: No module named online_models`

**Comment by yanmengqi** [comment]
@hiteshvaidya I think you should download a new version of Interactive_NMT, it is a different branches of nmt-keras. you can download it at address:https://github.com/lvapeab/nmt-keras/tree/interactive_NMT
