### ISSUE TITLE
models not saved after each epoch

### ISSUE THREAD

**Issue by hiteshvaidya** [lvapeab/nmt-keras#41]
I tried running your code as it is. But the models are not getting saved after each epoch. There's just one model that was saved with the name, *EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001*

Please suggest a possible solution
Thanks

**Comment by lvapeab** [comment]
Weird. 
`EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001` should be the folder where to save it the models.

Can you please check inside this folder?

**Comment by hiteshvaidya** [comment]
Oh.. yes, I got the files. Thanks. You should probably update the following code for testing the translation,
`python sample_ensemble.py 
             --models trained_models/tutorial_model/epoch_1 \ 
                      trained_models/tutorial_model/epoch_2 \
             --dataset datasets/Dataset_tutorial_dataset.pkl \
             --text examples/EuTrans/test.en`
