### ISSUE TITLE
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[50,68,394054]

### ISSUE THREAD

**Issue by hiteshvaidya** [lvapeab/nmt-keras#42]
I am trying to use this code for English-Hindi translation. Following are the details of my corpus
training file = 1761368 lines
testing file = 3537 lines
validation file = 3537 lines
I have a server with 4 GTX 1080 GPUs of 8 Gb each. The htop command shows the following result when this program is not running.
![image](https://user-images.githubusercontent.com/14166608/38672726-ad9400ba-3e6c-11e8-9a57-677304f2bc9d.png)

I tried reducing batch size to 16 but nothing worked. Also, I have edited following parameters in `config` file, `MAX_INPUT_TEXT_LEN = 11351` and `MAX_OUTPUT_TEXT_LEN = 7898`. I tried to run the program with default parameters but still, the same error persists.

Please help.
Thanks

**Comment by lvapeab** [comment]
It seems you have a way too large vocabulary (394054 words!). 

I you must use a shortlist of the vocabulary (e.g. keep the top-K frequent words, mapping the rest to an unknown token). You can easily set this with the `INPUT_VOCABULARY_SIZE` and `OUTPUT_VOCABULARY_SIZE` options.

Moreover, the options `MAX_INPUT_TEXT_LEN = 11351`  `MAX_OUTPUT_TEXT_LEN = 7898` indicate the max number of words allowed in each sentence. You probably want to  reduce this number (to e.g. 80 words (this depends on your corpora).

Finally, I recommend you to have a look to sub-word preprocessing methods, such as [byte-pair-encoding](https://github.com/rsennrich/subword-nmt/), which are effective when dealing with large vocabularies.

**Comment by hiteshvaidya** [comment]
Thank you so much for your help. I made following changes as per your suggestion and I am able to train.
MAX_INPUT_TEXT_LEN = 100
MAX_OUTPUT_TEXT_LEN = 100
INPUT_VOCABULARY_SIZE = 50000
OUTPUT_VOCABULARY_SIZE = 50000
BATCH_SIZE = 50

However, it seems that training is not using  any GPU. I am running it using tensorflow-gpu-1.3 backend. I didn't find any option for setting the parameters like gpuid or multiple gpuids etc.  Please let me know if there is any way to use  GPUs to speed up the training.

Thank you.

**Comment by lvapeab** [comment]
This is probably related to your Keras'/Tensorflow configuration. 
I've never tried multi-gpu configuration, but on a single GPU, it should work.

**Comment by lvapeab** [comment]
Thanks for the info ^^
