### ISSUE TITLE
ImportError: cannot import name AlphaRegularizer

### ISSUE THREAD

**Issue by Jeen-Hur** [lvapeab/nmt-keras#44]
Hi !
Thanks for your kind to evaluate NMT-KERAS. 
I did try several versions of keras to deal with the trouble of "ImportError: cannot import name AlphaRegularizer"
Could you help me?

----> 6 from model_zoo import TranslationModel
      7 import utils
      8 from keras_wrapper.cnn_model import loadModel

D:\python-2.7.14\src\voice\nmt-py27-win-keras\nmt-keras\model_zoo.py in <module>()
      5 from keras.models import model_from_json, Model
      6 from keras.optimizers import Adam, RMSprop, Nadam, Adadelta, SGD, Adagrad, Adamax
----> 7 from keras.regularizers import l2, AlphaRegularizer
      8 from keras_wrapper.cnn_model import Model_Wrapper
      9 from keras_wrapper.extra.regularize import Regularize

ImportError: cannot import name AlphaRegularizer

**Comment by lvapeab** [comment]
Hi @Jeen-Hur ,

please, make sure you're using [our Keras fork](https://github.com/MarcBS/keras)

**Comment by aagusuab** [comment]
HI @Ivapeab!
How can I install your version of Keras fork using conda?
Thank you in advance!

**Comment by catskillsresearch** [comment]
I am trying to install Anadonda Python 3.7 for Windows and then tensorflow-gpu and then nmt-keras.  Per above, your version of keras needs to be installed first.  But then conda will try to uninstall it or install another keras on top of it.  Would it be possible for you to try doing an install from scratch of Anaconda and nmt-keras on a Windows PC and tell us how you navigate around conda's dependency checking?

**Comment by sudhinbabu** [comment]
try 
installing from the correct repository 
```sh
pip install git+https://github.com/MarcBS/keras.git
```
i faced the same issue when i tried
```sh
pip install keras
```
