### ISSUE TITLE
Invalid requirement: --allow-external keras

### ISSUE THREAD

**Issue by yanmengqi** [lvapeab/nmt-keras#48]
I 'd like to install the Interactive_NMT at my new Mac.I have downloaded the Multimodal_keras_wrapper follow the step.but now ,I have something wrong with my code.
I am following this guide from your github,this is the guide address:https://github.com/lvapeab/multimodal_keras_wrapper/blob/master/README.md

when I have excuted the code:git clone https://github.com/MarcBS/multimodal_keras_wrapper.git
export PYTHONPATH=$PYTHONPATH:/path/to/multimodal_keras_wrapper

and when I run this code:pip install -r requirements.txt
there is something wrong happened, this is the wrong code:

Usage: pip [options]

Invalid requirement: --allow-external keras
pip: error: no such option: --allow-external

Thank you very much!

**Comment by lvapeab** [comment]
If you want to use the Interactive_NMT branch, you should download my fork of  `Multimodal_keras_wrapper`, from https://github.com/lvapeab/multimodal_keras_wrapper.git. Indeed, there's a wrong link in that README, I'll fix it.

It seems the --allow-external was deprecated in pip. I've just updated the directory.

**Comment by yanmengqi** [comment]
Thank you！
