### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by yanmengqi** [lvapeab/nmt-keras#50]
I am running the default dataset with nmt-keras, but when I run the command :python main.py.After 1 epoch,there are something wrong with the following bug code:

Epoch 2/500
102/198 [==============>...............] - ETA: 1:17 - loss: 2.4363
[22/05/2018 07:57:59] <<< Predicting outputs of train set >>>
Starting dataLoad_process_0...
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/keras_wrapper/dataset.py", line 105, in dataLoad
    dataAugmentation=data_augmentation)
  File "build/bdist.linux-x86_64/egg/keras_wrapper/dataset.py", line 3241, in getXY
    x = eval('self.X_' + set_name + '[id_in][last:new_last]')
  File "<string>", line 1, in <module>
TypeError: only integer scalar arrays can be converted to a scalar index
Can you tell me why this issue happened and how to fix it?

There are something I want to tell you is that I have tried to use nmt-keras to train a Chinese-English models,also it's using abality is not good,but I think I will make it perfect in the future,Thanks for your help.

**Comment by lvapeab** [comment]
Hi,
are you using the [PARALEL_LOADERS](https://github.com/lvapeab/nmt-keras/blob/master/config.py#L153) in the config?

**Comment by yanmengqi** [comment]
Yes,the parallel_loaders=1
So,I should change this number?

**Comment by lvapeab** [comment]
Weird. No, you shouldn't change it. Please, make sure you're using the last version of the  `keras_wrapper` repo (`git pull`) .

**Comment by yanmengqi** [comment]
thank you . I have already solved this problem.
