### ISSUE TITLE
How do we implement bidirection translation using the same model?

### ISSUE THREAD

**Issue by frajos100** [lvapeab/nmt-keras#51]
How do we implement bidirection translation using the same model i.e. From Spanish to English and from English to Spanish? Is there any configurations in the config.py that needs to be changed?

**Comment by lvapeab** [comment]
Hi, 

I never tried to train a multilingual model. According to [Johnson et al.](https://www.aclweb.org/anthology/Q/Q17/Q17-1024.pdf), this can be easily done in a pre/post processing step with a conventional NMT system.

Cheers.

**Comment by frajos100** [comment]
Hi,
This is not related to multilingual but bi direction translation from English to French and vice versa.
Only one language pair. How do we perform the training?

**Comment by lvapeab** [comment]
Well, it is a particular case: You can see En->Fr and Fr->En as two language pairs.
