### ISSUE TITLE
Using NMT-Keras how could we create a model that can perform bi-directional translation

### ISSUE THREAD

**Issue by frajos100** [lvapeab/nmt-keras#52]
Using NMT-Keras how could we create a model that can perform bi-directional translation I..e. the model should be able to translate from French to English and then back from English to French.
How could we set up training of such a model using NMT-Keras?

**Comment by lvapeab** [comment]
Hi, 

I already answered you in a previous issue (https://github.com/lvapeab/nmt-keras/issues/51). Please, do not open duplicated issues.
