### ISSUE TITLE
Is the transformer model current implementation suggested or it's still in beta?

### ISSUE THREAD

**Issue by JohannesTK** [lvapeab/nmt-keras#57]
As you bring out the transformer model is: "Somewhat untested and missing the tied embeddings." and https://github.com/lvapeab/nmt-keras/issues/54

Is the current state good for use or it's still in beta?

**Comment by lvapeab** [comment]
Hi,

at its  current state, it misses  these both features. I've made some tests though, and it achieves good performance values. To overcome https://github.com/lvapeab/nmt-keras/issues/54, you can set `OPTIMIZED_SEARCH = False` in `config.py`, but the sampling process will be slightly slow.

I also have a version of the tied embeddings, but I faced this problem: https://github.com/keras-team/keras/issues/10485, that I've been unable to solve. 

I currently don't have a lot of time to spend implementing this, so advances may be slow.

Any help is appreciated though ^^

**Comment by lvapeab** [comment]
A first version of tied embeddings was added at 4ff65e041bc43763977a2c1183279ce9279fda47. I'm closing this.
