### ISSUE TITLE
How to build a character sequence to sequence model?

### ISSUE THREAD

**Issue by anant10** [lvapeab/nmt-keras#58]

**Comment by lvapeab** [comment]
Hi, 

you can pre-process your data files and split the charaters from words. Or you can use the tokenize-detokenize options in the `config.py`:

```
TOKENIZATION_METHOD = 'tokenize_none_char'
DETOKENIZATION_METHOD = 'detokenize_none_char'
APPLY_DETOKENIZATION = True
```


This feature may have some problem, as it is not thoroughly tested. Moreover, if you use a naive NMT model for character seq2seq, it may perform poorly. In case you want to implement an additional model, you shoud modify the `model_zoo.py` file.

Cheers.

**Comment by anant10** [comment]
Thanks lvapeab , 
its working but bleu scores  are worse. In the validation but the prediction is good enough.
