### ISSUE TITLE
What about tansfer learning? 

### ISSUE THREAD

**Issue by lchunleo** [lvapeab/nmt-keras#62]
Hi
Is it possible to do transfer learning for different language translation , how can I do so? Thank you v much

**Comment by lvapeab** [comment]
Yes, it should be possible.  I never tried to do this, but according to [Johnson et al.](https://www.aclweb.org/anthology/Q/Q17/Q17-1024.pdf), this can be easily done in a pre/post processing step with a conventional NMT system.

**Comment by lchunleo** [comment]
Do the current implementation allow me to 
1) Train based on the given language 
2) Freeze the encoder 
3) Train again with another language? 

i tried to use the RELOAD_EPOCH to set to another last trained epoch to allow the previous given language trained weights to be applied and REBUILD_DATASET to set to False.  But can't get it to work. Any advise?

**Comment by lvapeab** [comment]
Yes, it should be possible. You should set `TRAINABLE_ENCODER = False` in the `config.py` and set the path to the new data (setting properly `DATA_ROOT_PATH` and/or `TEXT_FILES`).

What problems did you
