### ISSUE TITLE
repetition in translation

### ISSUE THREAD

**Issue by lchunleo** [lvapeab/nmt-keras#63]
Hi

 i tried with a 36K training dataset with 10K validation data set , trained with the default settings with 25 epochs . However, when i do a translation from foreign language to english, it shows weird result as there is no context meaning.

My dataset r comprised of words and sentences that of typical general writing. So is it possible my datasets does not show variant of the sentences structure? If so how much variant do I need? 

(Ground truth Foreign language-equivalent English meaning: Besides having to apply for a licence from the Land Transport Authority, all dockless bike-sharing operators will have to regulate their fleet sizes, pay a registration fee for each bicycle and ensure that their bikes are parked in designated areas.

(Translated english meaning words)

notified a having of a driver's from a driver's license dictionary of the joint adults dictionary of the joint adults dictionary of the brought up to the battery power for friends for some bicycle and made up with their bicycle and made up with their bicycle and made up with their bicycle and made their bicycle and made up with their bicycle and made up with their bicycle and made their bicycle and made up with their bicycle and made up with their bicycle and made their bicycle and made up with their bicycle and made up with their

![epoch_24](https://user-images.githubusercontent.com/24416494/42409099-bd507914-8207-11e8-8e8f-a17f7ebf4f64.jpg)

**Comment by lvapeab** [comment]
This is a typical example of a ill-trained model. 
The standard configuration set in the `config.py` is meant to be a minimal system. You'll definitely need to update the configuration to another one that suits better your problem. As I said to you (https://github.com/lvapeab/nmt-keras/issues/56), you'll need to change the hyperparameters.

**Comment by lchunleo** [comment]
thank you for your reply. Due to my inexperience and unsure what i seeing is because of my dataset issue (not enough variants or too little)or due to hyperparameters (which i had made some minor changes but seeing not much changes). Thanks for your guidance.  i will definitely relook into the hyperparameters.
