### ISSUE TITLE
Theano backend with "USE_TF_OPTIMIZER = True"

### ISSUE THREAD

**Issue by ptamas88** [lvapeab/nmt-keras#68]
Hello!
I am trying to run NMT-Keras in an nvidia-docker container but it uses Theano backend no matter what I set in USE_TF_OPTIMIZER parameter in the config file. I haven't changed anything yet, just wanna see it running.
I installed CUDA 9.0 with CudNN on the host and tensorflow-gpu in the container. If I run
```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```
i cac see the GPUs.
Can you help me what to change for tensorflow gpu usage?
Thanks!

**Comment by lvapeab** [comment]
Hi,

you should set the `Keras` backend to `tensorflow`. Edit your `$HOME/.keras/keras.json` and switch the backend option to tensorflow.

See: https://keras.io/backend/

Cheers

**Comment by ptamas88** [comment]
@ @lvapeab Thenak you very much, it's so obvious I forgot it :|
