### ISSUE TITLE
Strange Characters during Evaluation steps ?

### ISSUE THREAD

**Issue by mohammedayub44** [lvapeab/nmt-keras#72]
Hi @lvapeab ,

During evaluation I see some inconsistencies  in my  Hypothesis and reference sentences that have been decoded. (Like \xc3\xa9 , \xc3\xb3 etc. ) Is there a way to preserve original encodings throughout training and testing. My test file does contain the original encoding appropriately. 

Source     (2): b'<unk>  Protection of single-, double-, and multiple-row rack storage without solid shelves for Class I through Class IV commodities shall be in accordance with Table <unk>'
Hypothesis (2): b'<unk> **Protecci\xc3\xb3n** de los sistemas de **protecci\xc3\xb3n** contra incendios y de los sistemas de Clase II deben cumplir con lo establecido en la **secci\xc3\xb3n** Table'
Reference  (2): b'<unk> La protecci\xc3\xb3n del almacenamiento en **estanter\xc3\xadas** de una, doble y **m\xc3\xbaltiple** fila sin estantes macizos para **mercanc\xc3\xadas** Clase I a Clase IV debe estar de acuerdo con la Tabla <unk>'

**Original** -  b'<unk> **ProtecciÃ³n** de los sistemas de **ProtecciÃ³n** contra incendios y de los sistemas de Clase II deben cumplir con lo establecido en la **secciÃ³n** Table

Any help appreciated !

-Mohammed Ayub

**Comment by mohammedayub44** [comment]
Default encoding on my Ubuntu System seems to be ANSI-Latin1 ... is there an option in keras_wrapper Dataset object to pass the utf-8 encoded text. 
Thanks !

-Mohammed Ayub

**Comment by howlinghuffy** [comment]
I had to update the environment variables LC_ALL, LANG and LANGUAGE to one of the utf-8 encodings available in my Ubuntu system to get around this.  It now reads my files correctly in UTF-8

**Comment by mohammedayub44** [comment]
Thanks @howlinghuffy  This worked. Running the `locale` command my `LC_ALL` and `LANGUAGE` variables were empty. I changed all of them to the same value of UTF-8.
