### ISSUE TITLE
Dev(Val) and Test dataset

### ISSUE THREAD

**Issue by qazs** [lvapeab/nmt-keras#74]
Hi,
I'm a bit confused over dev(val) and test datasets in nmt-keras.
May I know which is used 
- during training
- after training to test the performance?

**Comment by lvapeab** [comment]
Hi, 
as additional reading, you can see the [Chapter 5](http://www.deeplearningbook.org/contents/ml.html) of the Deep Learning book (Goodfellow et al., 2016), regarding validation sets (Sections 5.2 and 5.3).
