### ISSUE TITLE
BLEU score on WMT 2014 Englishto-German translation task

### ISSUE THREAD

**Issue by christopher5106** [lvapeab/nmt-keras#76]
Hi,
Do you have it ?
Thx

**Comment by lvapeab** [comment]
Hi, 
using an encoder-decoder similar to the one described [here](https://github.com/lvapeab/nmt-keras/blob/master/examples/configs/config_rnn.py), and the data directly taken from [the Standford NLP group](https://nlp.stanford.edu/projects/nmt/) I obtained 19.7.

**Comment by christopher5106** [comment]
Thank you
