### ISSUE TITLE
How to get the N-best lists and to rerank them? 

### ISSUE THREAD

**Issue by brentylw** [lvapeab/nmt-keras#81]
I am new to nmt and excited to run main.py successfully. I am interested in the N-best lists but don't know how to draw them out. Thanks.

**Comment by lvapeab** [comment]
You have to pass the option `--n-best` to the [sample_ensemble.py](https://github.com/lvapeab/nmt-keras/blob/master/sample_ensemble.py) script. For more information, see this: https://github.com/lvapeab/nmt-keras/blob/master/examples/documentation/ensembling_tutorial.md
