### ISSUE TITLE
Excluding word from translation

### ISSUE THREAD

**Issue by qazs** [lvapeab/nmt-keras#83]
Hi, how can I exclude a word from translation? Or is there a way to ensure a specific word will not get translated?

**Comment by qazs** [comment]
Yes,
For example these sentences:
'I have a **dog** at home'.
'Ich habe einen **dog** zu Hause'

The word 'dog', or any other word I specified should remain untranslated, can this be achieved?

**Comment by lvapeab** [comment]
Currently, we don't have implemented this feature. It could be achieved following the aforementioned unknown replacement strategy. Feel free to implement it :)

**Comment by qazs** [comment]
Hi @lvapeab I created a mapping of words and generated mapping.en_cn.pkl. And in my config.py I set `POS_UNK = True` and `HEURISTIC = 1`, but the sampled result didn't follow the mapping. The unknown words were stripped, did I miss out anything?

**Comment by lvapeab** [comment]
Hi @qazs ,

I just implemented this. 

I've added an option `GLOSSARY` to the `config.py` file, in which you can set a glossary containing the desired substitutions. 

This glossary can be obtained from a plain text file with tje script located in [utils](https://github.com/lvapeab/nmt-keras/blob/master/utils/build_glossary.py) . Its usage is the following:

```python utils/build_glossary.py --glossary glossary.txt --dest glossary.pkl```

Now you can use the `glossary.pkl`.

So, for instance, say I have my model and I want to translate the `dev` set. I'd run `sample_ensemble.py`:

```
python sample_ensemble.py --dataset datasets/Dataset_EuTrans_esen.pkl --text examples/EuTrans/dev.es --dest dev.hyp.en --models trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_7
```

So, for the source sentences

> lléveme el equipaje al coche .
> por favor , ¿ les importaría llevar nuestras bolsas a la habitación ?

I obtain the translations:

> send my luggage to the car .
> would you mind sending our bags to the room , please ?

Now, I have defined my `glossary.txt` with the substitutions:

```
equipaje equipaje
bolsas BAGS!!
```

Next, I  run the sampling process taking into account this file:

```
python sample_ensemble.py --dataset datasets/Dataset_EuTrans_esen.pkl --text examples/EuTrans/dev.es --glossary glossary.pkl --dest dev.hyp.glos --models trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_7
```

If the attention mechanism is aligning a word existing in `glossary.pkl`, it will be replaced by the corresponding substitution. So, the output now is:

> send my **equipaje** to the car .
> would you mind sending our **BAGS!!** to the room , please ?

You can specify arbitrary substitutions, including untranslated words (e.g. `equipaje` in the example above).

P.S: A side note: This strategy relies entirely on the attention mechanism for performing the substitutions. So, it may have undesired side effects (e.g. the attention mechanism can spend its attention unnaturally or several times on the same word). Other strategies may work better, depending on each use case.
