### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jksignity** [lvapeab/nmt-keras#85]
Hi

I've trained the model on around 200000+ pairs of data and around epoch_14, I'm testing on my test data.

I'm doing this on Google colab and it takes around 90+ seconds to generate result on around 950 test inputs. Is this normal for the test to take this much time? or should I test this on some powerful GPU server?

**Comment by lvapeab** [comment]
Hi,
90/950~= 0.1s per sentence. I think this is normal. Installing `cupy` and `CuDNN` can accelerate the process.

**Comment by jksignity** [comment]
Thank you, it was my mistake. I did the wrong calculation.
