### ISSUE TITLE
Conditional Layer 

### ISSUE THREAD

**Issue by PVinay737** [lvapeab/nmt-keras#87]
Can you elaborate a bit on the usage of Conditional GRU/LSTM over a regular GRU/LSTM ? What are the advantages and disadvantages of it ?

P.S
Also Adding convolution layers with filter sizes can lead to better generalizations  during decoding

**Comment by lvapeab** [comment]
A conditional GRU/LSTM consists in two GRU/LSTM activations  with an attention mechanism in between. 
The first GRU/LSTM  computes an intermediate hidden state according to the previous output. Next, the attention mechanism is applied for weighting the annotations of the encoder with respect to it, computing a context vector. This context vector is the input to the second GRU/LSTM. See [page 2](https://arxiv.org/pdf/1703.04357.pdf) or [Sec 3](https://arxiv.org/pdf/1802.03594.pdf) from these papers.

The advantages are that usually conditional units perform better than regular ones. 

The disadvatages are that conditional units  have more parameters and computational complexity than regular ones.

Overall, I think the usage of conditional units pays off.

**Comment by PVinay737** [comment]
Thanks for the clarification !
