### ISSUE TITLE
ImportError: No module named keras_wrapper.dataset

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#9]
Hi~
I use the line of Cloning https://github.com/MarcBS/keras with error, so i download the keras-master.zip from chrome, copy keras under nmt-keras/src after unzip. When i execute python main.py, there is still a error.

`Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from data_engine.prepare_data import build_dataset
  File "/home/hanyaqian/coders/keras-tutorial/nmt-keras/data_engine/prepare_data.py, in <module>
    from keras_wrapper.dataset import Dataset, saveDataset, loadDataset
ImportError: No module named keras_wrapper.dataset
`
Can you give me some help? Thanks!

**Comment by hanyaqian** [comment]
The problem has solved. thanks for your work.

**Comment by hiteshvaidya** [comment]
@hanyaqian how did you solve it?
