### ISSUE TITLE
Resume training with new data

### ISSUE THREAD

**Issue by aklam** [lvapeab/nmt-keras#92]
Hi!
I'm getting the following error when I load my model and try to resume training on new data.

ValueError: Dimension 1 in both shapes must be equal, but are 7539 and 30000. Shapes are [32,7539] and [32,30000]. for 'Assign_61' (op: 'Assign') with input shapes: [32,7539], [32,30000].

Background, I initially trained the model on a large corpus of text. I have re-loaded the model successfully but am having trouble getting it to train on new data. The new corpus of text is substantially smaller than the original corpus so I suspect there is some issue with vocabulary size??

I have the following parameters when I reload the model:
params['RELOAD'] = 1
params['RELOAD_EPOCH'] = True
params['REBUILD_DATASET'] = True
params['DATA_ROOT_PATH'] = 'query_to_reply/Dataset_Cornell.pkl'

Dataset_Cornell.pkl contains the smaller dataset

**Comment by aklam** [comment]
Hi! 
Thank you for your help! I have a couple more questions.
I am getting the following error:
ValueError: No data provided for "source_text". Need data for each key in: ['source_text', 'state_below']

1) For the model params, INPUT_VOCABULARY_SIZE and OUTPUT_VOCABULARY_SIZE should I set that equal to the new or the old dataset?

2) Should the vocabularies argument in TranslationModel be set to the new dataset vocabulary or the old dataset vocabulary?

3) When restarting training, with nmt_model.trainNet, should I input the new dataset or old dataset? From my understanding of your above reply, 
DATA_ROOT_PATH = '/home/data/other_task'
TEXT_FILES = {'train': 'training2.'}
swaps out the 'train' input in the old dataset with the data from training2

Thank you in advance for your help!

**Comment by lvapeab** [comment]
Hi,
I'm not sure whether it's a vocabulary-related problem or not. If you are updating your dataset for training on new data, you should set `compute_state_below=True` in your `update_dataset_from_file` call. 

-- 

 If your error persists, what are the values of `params['OUTPUT_VOCABULARY_SIZE']`and the last layer of the model? (it's in the summary of the model printed by Keras).

**Comment by aklam** [comment]
After messing around a lot with the data inputs/outputs, I eventually got it to work.
Instead of calling update_dataset_from_file, I just overwrote the inputs like so
ds.setInput('data/Cornell_train_2.query',
    'train',
    type='text',
    id='source_text',
    tokenization='tokenize_basic',
    #build_vocabulary=True,
    pad_on_batch=True,
    fill='end',
    max_text_len=30,
    min_occ=0,
    overwrite_split=True)

ds.setInput('data/Cornell_train_2.reply',
    'train',
    type='text',
    id='state_below',
    required=False,
    tokenization='tokenize_basic',
    pad_on_batch=True,
    #build_vocabulary='target_text_2',
    offset=1,
    fill='end',
    max_text_len=30,
    overwrite_split=True)

ds.setOutput('data/Cornell_train_2.reply',
    'train',
    type='text',
    id='target_text',
    tokenization='tokenize_basic',
    #build_vocabulary=True,
    pad_on_batch=True,
    sample_weights=True,
    max_text_len=30,
    min_occ=0,
    overwrite_split=True)
