### ISSUE TITLE
Standard deviation of Loss

### ISSUE THREAD

**Issue by aklam** [lvapeab/nmt-keras#93]
Is there a way to calculate the standard deviation of the Loss on the test set during evaluation? I know we get the total and the average loss on the test set. Or even better, could the loss for each test value be outputted somehow?

**Comment by lvapeab** [comment]
Hi,

this feature is currently not supported.  Its implementation probably would require to modify the [EvalPerformance](https://github.com/lvapeab/multimodal_keras_wrapper/blob/661a3b61d96cd4390d117d005c55ab61b97afc1f/keras_wrapper/extra/callbacks.py#L65) callback and the output given by the [Beam Search](https://github.com/lvapeab/multimodal_keras_wrapper/blob/661a3b61d96cd4390d117d005c55ab61b97afc1f/keras_wrapper/model_ensemble.py#L311-L325) for returning the costs. 

I don't have much time for implementing this, but feel free to do it yourself and ask for any doubts.

Cheers.
