### ISSUE TITLE
weird: no json files in trained models folder

### ISSUE THREAD

**Issue by brentylw** [lvapeab/nmt-keras#95]
It is very strange that no any json file written in my trained models folder.
I trained my model on a remote gpu machine and immediately run sample_ensemble.py, then I got the predicted result txt. But after I close the command window and then rerun the command sample_ensemble.py, an error occured: FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/EuTrans/epoch_1_structure.json'
Why are the json files  not written into the folder?

**Comment by lvapeab** [comment]
Hi,

can you access to the folder `trained_models/EuTrans/ ` when you reopen the command window? 

Please make `ls` on the folder and show the results. Also, what exact command did you execute?

**Comment by trungjune** [comment]
I also have a similar question

**Comment by lvapeab** [comment]
It seems your errors are similar to https://github.com/lvapeab/nmt-keras/issues/102#issuecomment-482454356. Please, check out you are executing the `sample_ensemble.py` script correctly. If not, please, let me know the exact command you are running.

**Comment by trungjune** [comment]
viegrid@viegrid-SV:~/trungth/testpip/nmt-keras/trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001$ ls
config.pkl                  epoch_26_Model_Wrapper.pkl  epoch_42_init.h5
epoch_10.h5                 epoch_26_next.h5            epoch_42_Model_Wrapper.pkl
epoch_10_init.h5            epoch_27.h5                 epoch_42_next.h5
epoch_10_Model_Wrapper.pkl  epoch_27_init.h5            epoch_4.h5
epoch_10_next.h5            epoch_27_Model_Wrapper.pkl  epoch_4_init.h5
epoch_11.h5                 epoch_27_next.h5            epoch_4_Model_Wrapper.pkl
epoch_11_init.h5            epoch_28.h5                 epoch_4_next.h5
epoch_11_Model_Wrapper.pkl  epoch_28_init.h5            epoch_5.h5
epoch_11_next.h5            epoch_28_Model_Wrapper.pkl  epoch_5_init.h5
epoch_12.h5                 epoch_28_next.h5            epoch_5_Model_Wrapper.pkl
epoch_12_init.h5            epoch_29.h5                 epoch_5_next.h5
epoch_12_Model_Wrapper.pkl  epoch_29_init.h5            epoch_6.h5
epoch_12_next.h5            epoch_29_Model_Wrapper.pkl  epoch_6_init.h5
epoch_13.h5                 epoch_29_next.h5            epoch_6_Model_Wrapper.pkl
epoch_13_init.h5            epoch_2.h5                  epoch_6_next.h5
epoch_13_Model_Wrapper.pkl  epoch_2_init.h5             epoch_7.h5
epoch_13_next.h5            epoch_2_Model_Wrapper.pkl   epoch_7_init.h5
epoch_14.h5                 epoch_2_next.h5             epoch_7_Model_Wrapper.pkl
epoch_14_init.h5            epoch_30.h5                 epoch_7_next.h5
epoch_14_Model_Wrapper.pkl  epoch_30_init.h5            epoch_8.h5
epoch_14_next.h5            epoch_30_Model_Wrapper.pkl  epoch_8_init.h5
epoch_15.h5                 epoch_30_next.h5            epoch_8_Model_Wrapper.pkl
epoch_15_init.h5            epoch_31.h5                 epoch_8_next.h5
epoch_15_Model_Wrapper.pkl  epoch_31_init.h5            epoch_9.h5
epoch_15_next.h5            epoch_31_Model_Wrapper.pkl  epoch_9_init.h5
epoch_16.h5                 epoch_31_next.h5            epoch_9_Model_Wrapper.pkl
epoch_16_init.h5            epoch_32.h5                 epoch_9_next.h5
epoch_16_Model_Wrapper.pkl  epoch_32_init.h5            tensorboard_logs
epoch_16_next.h5            epoch_32_Model_Wrapper.pkl  val.coco
epoch_17.h5                 epoch_32_next.h5            val_epoch_10_output_0.pred
epoch_17_init.h5            epoch_33.h5                 val_epoch_11_output_0.pred
epoch_17_Model_Wrapper.pkl  epoch_33_init.h5            val_epoch_12_output_0.pred
epoch_17_next.h5            epoch_33_Model_Wrapper.pkl  val_epoch_13_output_0.pred
epoch_18.h5                 epoch_33_next.h5            val_epoch_14_output_0.pred
epoch_18_init.h5            epoch_34.h5                 val_epoch_15_output_0.pred
epoch_18_Model_Wrapper.pkl  epoch_34_init.h5            val_epoch_16_output_0.pred
epoch_18_next.h5            epoch_34_Model_Wrapper.pkl  val_epoch_17_output_0.pred
epoch_19.h5                 epoch_34_next.h5            val_epoch_18_output_0.pred
epoch_19_init.h5            epoch_35.h5                 val_epoch_19_output_0.pred
epoch_19_Model_Wrapper.pkl  epoch_35_init.h5            val_epoch_1_output_0.pred
epoch_19_next.h5            epoch_35_Model_Wrapper.pkl  val_epoch_20_output_0.pred
epoch_1.h5                  epoch_35_next.h5            val_epoch_21_output_0.pred
epoch_1_init.h5             epoch_36.h5                 val_epoch_22_output_0.pred
epoch_1_Model_Wrapper.pkl   epoch_36_init.h5            val_epoch_23_output_0.pred
epoch_1_next.h5             epoch_36_Model_Wrapper.pkl  val_epoch_24_output_0.pred
epoch_20.h5                 epoch_36_next.h5            val_epoch_25_output_0.pred
epoch_20_init.h5            epoch_37.h5                 val_epoch_26_output_0.pred
epoch_20_Model_Wrapper.pkl  epoch_37_init.h5            val_epoch_27_output_0.pred
epoch_20_next.h5            epoch_37_Model_Wrapper.pkl  val_epoch_28_output_0.pred
epoch_21.h5                 epoch_37_next.h5            val_epoch_29_output_0.pred
epoch_21_init.h5            epoch_38.h5                 val_epoch_2_output_0.pred
epoch_21_Model_Wrapper.pkl  epoch_38_init.h5            val_epoch_30_output_0.pred
epoch_21_next.h5            epoch_38_Model_Wrapper.pkl  val_epoch_31_output_0.pred
epoch_22.h5                 epoch_38_next.h5            val_epoch_32_output_0.pred
epoch_22_init.h5            epoch_39.h5                 val_epoch_33_output_0.pred
epoch_22_Model_Wrapper.pkl  epoch_39_init.h5            val_epoch_34_output_0.pred
epoch_22_next.h5            epoch_39_Model_Wrapper.pkl  val_epoch_35_output_0.pred
epoch_23.h5                 epoch_39_next.h5            val_epoch_36_output_0.pred
epoch_23_init.h5            epoch_3.h5                  val_epoch_37_output_0.pred
epoch_23_Model_Wrapper.pkl  epoch_3_init.h5             val_epoch_38_output_0.pred
epoch_23_next.h5            epoch_3_Model_Wrapper.pkl   val_epoch_39_output_0.pred
epoch_24.h5                 epoch_3_next.h5             val_epoch_3_output_0.pred
epoch_24_init.h5            epoch_40.h5                 val_epoch_40_output_0.pred
epoch_24_Model_Wrapper.pkl  epoch_40_init.h5            val_epoch_41_output_0.pred
epoch_24_next.h5            epoch_40_Model_Wrapper.pkl  val_epoch_42_output_0.pred
epoch_25.h5                 epoch_40_next.h5            val_epoch_4_output_0.pred
epoch_25_init.h5            epoch_41.h5                 val_epoch_5_output_0.pred
epoch_25_Model_Wrapper.pkl  epoch_41_init.h5            val_epoch_6_output_0.pred
epoch_25_next.h5            epoch_41_Model_Wrapper.pkl  val_epoch_7_output_0.pred
epoch_26.h5                 epoch_41_next.h5            val_epoch_8_output_0.pred
epoch_26_init.h5            epoch_42.h5                 val_epoch_9_output_0.pred

**Comment by trungjune** [comment]
during the train with errors
[25/04/2019 09:54:40] <<< Saving model to trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001//epoch_2 ... >>>
/home/viegrid/trungth/testpip/nmt-keras/src/keras/keras/engine/saving.py:128: UserWarning: TensorFlow optimizers do not make it possible to access optimizer attributes or optimizer state after instantiation. As a result, we cannot save the optimizer as part of the model save file.You will have to compile your model again after loading it. Prefer using a Keras optimizer instead (see keras.io/optimizers).
  'TensorFlow optimizers do not '

**Comment by lvapeab** [comment]
So, following https://github.com/lvapeab/nmt-keras/issues/102#issuecomment-482454356, you should execute something like:

```
cd ~/trungth/testpip/nmt-keras/; python sample_ensemble.py --models trained_models/EuTrans_esen_AttentionRNNEncoderDecoder_src_emb_32_bidir_True_enc_LSTM_32_dec_ConditionalLSTM_32_deepout_linear_trg_emb_32_Adam_0.001/epoch_20 --dataset datasets/Dataset_EuTrans_enes.pkl --text examples/EuTrans/test.en
```

**Comment by trungjune** [comment]
Thanks，It works

**Comment by sampathkethineedi** [comment]
Hey it still get the error: 
`FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/en_fr_test/epoch_4_structure.json'`

Running the command:
`python sample_ensemble.py --models trained_models/en_fr_test/epoch_4 --dataset datasets/Dataset_en_fr_test.pkl --text examples/EN_FR/test.fr`

Contents of en_fr_test:
`epoch_1.h5                      epoch_2.h5                      epoch_3.h5                      epoch_4.h5                      val.sacrebleu
epoch_1.jpg                     epoch_2.jpg                     epoch_3.jpg                     epoch_4.jpg                     val_epoch_1_output_0.pred
epoch_1_Model_Wrapper.pkl       epoch_2_Model_Wrapper.pkl       epoch_3_Model_Wrapper.pkl       epoch_4_Model_Wrapper.pkl       val_epoch_2_output_0.pred
epoch_1_init.h5                 epoch_2_init.h5                 epoch_3_init.h5                 epoch_4_init.h5                 val_epoch_3_output_0.pred
epoch_1_next.h5                 epoch_2_next.h5                 epoch_3_next.h5                 epoch_4_next.h5                 val_epoch_4_output_0.pred
`

**Comment by lvapeab** [comment]
Hi, 

can you please provide the full error trace?

**Comment by sampathkethineedi** [comment]
```
Using an ensemble of 1 models
[13/06/2020 12:00:07] <<< Loading model from trained_models/en_fr_test/epoch_4_Model_Wrapper.pkl ... >>>
[13/06/2020 12:00:07] <<< Loading model from trained_models/en_fr_test/epoch_4.h5 ... >>>
[13/06/2020 12:00:07] Unknown layer: PositionLayer
[13/06/2020 12:00:07] <<< Loading model from trained_models/en_fr_test/epoch_4_structure.json' ... >>>
Traceback (most recent call last):
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras_wrapper/saving.py", line 209, in loadModel
    compile=compile_model)
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: PositionLayer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample_ensemble.py", line 62, in <module>
    sample_ensemble(args, params)
  File "/Users/sampathkethineedi/PycharmProjects/nmt/nmt-keras/nmt_keras/apply_model.py", line 40, in sample_ensemble
    models = [loadModel(m, -1, full_path=True) for m in args.models]
  File "/Users/sampathkethineedi/PycharmProjects/nmt/nmt-keras/nmt_keras/apply_model.py", line 40, in <listcomp>
    models = [loadModel(m, -1, full_path=True) for m in args.models]
  File "/Users/sampathkethineedi/.conda/envs/voicenlp/lib/python3.7/site-packages/keras_wrapper/saving.py", line 214, in loadModel
    model = model_from_json(open(model_name + '_structure.json').read(),
FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/en_fr_test/epoch_4_structure.json'
```

**Comment by lvapeab** [comment]
Please, check that you are using [our Keras fork](https://github.com/MarcBS/keras). It seems you are using the original one.
